export const GET_COLOR_TYPES = new Map()
  .set('fire', 'bg-red-500')
  .set('grass', 'bg-green-500')
  .set('water', 'bg-blue-500')
  .set('flying', 'bg-indigo-500')
  .set('steel', 'bg-gray-500')
  .set('ice', 'bg-blue-500')
  .set('ghost', 'bg-indigo-500')
  .set('bug', 'bg-yellow-900')
  .set('poison', 'bg-indigo-500')
  .set('physic', 'bg-pink-500')
  .set('dragon', 'bg-red-500')
  .set('fairy', 'bg-green-500')
  .set('dark', 'bg-gray-500')
  .set('fighting', 'bg-yellow-500')
  .set('ground', 'bg-yellow-500')
  .set('undefined', 'bg-gray-500');
