export const GET_COLOR_TYPES = new Map()
  .set('fire', 'text-red-700')
  .set('grass', 'text-green-700')
  .set('water', 'text-blue-700')
  .set('flying', 'text-indigo-700')
  .set('steel', 'text-gray-700')
  .set('ice', 'text-blue-700')
  .set('ghost', 'text-indigo-700')
  .set('bug', 'text-yellow-900')
  .set('poison', 'text-indigo-700')
  .set('physic', 'text-pink-700')
  .set('dragon', 'text-red-700')
  .set('fairy', 'text-green-700')
  .set('dark', 'text-gray-700')
  .set('fighting', 'text-yellow-700')
  .set('ground', 'text-yellow-700');
