export const GET_COLOR_TYPES = new Map()
  .set('fire', 'text-red-500')
  .set('grass', 'text-green-500')
  .set('water', 'text-blue-500')
  .set('flying', 'text-indigo-500')
  .set('steel', 'text-gray-500')
  .set('ice', 'text-blue-700')
  .set('ghost', 'text-indigo-500')
  .set('bug', 'text-indigo-500')
  .set('poison', 'text-indigo-500')
  .set('physic', 'text-pink-500')
  .set('dragon', 'text-red-500')
  .set('fairy', 'text-green-500')
  .set('dark', 'text-gray-700')
  .set('fighting', 'text-yellow-500')
  .set('ground', 'text-yellow-500');
